project:
  type: default
  output-dir: reports/quarto

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true
    code-tools: true
    theme: cosmo
    embed-resources: false

execute:
  echo: true
  warning: false
  message: false
  freeze: auto